baseURL = 'https://shmVirus.github.io'
languageCode = 'en-us'
title = '@shmVirus'
theme = 'PaperMod'

[[menu.main]]
  name = 'Blogs'
  url = '/blogs'
  weight = 1
[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 2
[[menu.main]]
  name = 'Resume'
  url = '/resume'
  weight = 3

[params.profileMode]
enabled = true
title = 'Sabbir Hosen Mamun'
subTitle = 'Linux and Open Source advocate'

[[params.socialIcons]]
name = "email"
url = "mailto:sabbir@disroot.org"
